name: Bug Report
description: Report an issue you encountered while using the app
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - astubenbord
body:
  - type: markdown
    attributes:
      value: |
        ###  Thank you for taking the time to fill out this bug report! 
        ---
        #### Before opening an issue, please double check [existing issues](https://github.com/astubenbord/paperless-mobile/issues).
        #### Have a question? 👉 [Start a new discussion](https://github.com/astubenbord/paperless-mobile/discussions/new)
        #### Have a feature request? 👉 [Use another form](https://github.com/astubenbord/paperless-mobile/issues/new/choose)

         If your issue involves the app crashing on startup, there is not much I can do without the logs. Therefore, please provide the logs as described in the section *Log output from the app* below.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A concise description of what you see. Also describe the expected behavior.
      placeholder: When I open the app, ...      
      value: "Describe what happened!"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Login with '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log output from the app
      description: Logs can be acquired by running `flutter logs` or `adb logcat | grep flutter` while your phone is connected to the computer. Providing logs significantly increases the chance of quickly finding and fixing the issue. If your app keeps crashing on startup, connect your device to your computer, run one of these commands in the terminal and only then start the app to get all the relevant logs.
      render: shell
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Screenshots helping to better understand the issue.
  - type: input
    id: server-version
    attributes:
      label: Paperless-ng*x Version
      description: What version of paperless are you running?
      placeholder: e.g. 1.17.4
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: Paperless-Mobile Version
      description: What version of the app are you using? The app version can be found in the "About this app" dialog located in the app drawer.
      placeholder: e.g. 3.0.1
    validations: 
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      description: What device are you running EDMS Mobile on?
      placeholder: e.g. Google Pixel 7 or iPhone 12 Pro
    validations: 
      required: true
  - type: input
    id: os-version
    attributes:
      label: Operating System Version
      description: What OS is installed on your device?
      placeholder: e.g. Android 13 or iOS 16.6
    validations: 
      required: true
  - type: input
    id: device-locale
    attributes:
      label: Device Locale
      description: What is the locale of your device?
      placeholder: e.g. german
    validations: 
      required: true
  - type: dropdown
    id: selected-locale
    attributes:
      label: Selected Locale
      description: What is the locale you have selected? If you have localization issues, please provide this information.
      options:
        - German
        - English (US)
        - English (UK)
        - French
        - Spanish
        - Catalan
        - Polish 
        - Russian
        - Turkish
        - Czech
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant details.
